import Foundation

/// Every user-visible string in the app, grouped by feature so a future
/// localization pass only has to touch this file.
enum L {
    enum Common {
        static let ok = "OK"
        static let cancel = "Cancel"
        static let save = "Save"
        static let delete = "Delete"
        static let add = "Add"
        static let edit = "Edit"
        static let done = "Done"
        static let close = "Close"
        static let retry = "Retry"
        static let loading = "Loading…"
        static let today = "Today"
        static let yesterday = "Yesterday"
        static let goal = "Goal"
        static let none = "None"
        static let error = "Something went wrong"
        static let noData = "No data yet"
        static let seeAll = "See all"
        static let optional = "Optional"
    }

    enum Tabs {
        static let today = "Today"
        static let coach = "Coach"
        static let food = "Food"
        static let fitness = "Fitness"
        static let more = "More"
    }

    enum Onboarding {
        static let welcomeTitle = "Meet Asclepius"
        static let welcomeSubtitle = "Your AI health coach, grounded in your real Apple Health data."
        static let pageCoachTitle = "A coach that knows you"
        static let pageCoachBody = "Chat with a coach that sees your sleep, workouts, nutrition and trends — and keeps a living plan for you."
        static let pageTrackTitle = "Track without friction"
        static let pageTrackBody = "Log meals with a photo, water with a tap, and lifts with a proper set editor. Everything counts toward your daily goals."
        static let pageHealthTitle = "Powered by Apple Health"
        static let pageHealthBody = "Steps, heart, sleep and body metrics sync automatically in the background. Your data stays yours."
        static let getStarted = "Get started"
        static let signInTitle = "Sign in"
        static let signInBody = "Sign in with Apple to keep your data private and synced securely."
        static let signInFailed = "Sign in didn't complete. Please try again."
        static let healthTitle = "Connect Apple Health"
        static let healthBody = "Asclepius reads your daily activity, heart, body and sleep data so your coach can actually coach. You choose what to share."
        static let healthAllow = "Connect Health"
        static let healthSkip = "Not now"
        static let healthDenied = "You can grant access later in Settings → Health → Data Access."
        static let syncTitle = "First sync"
        static let syncBody = "Bringing in your last two years of daily health data. This takes a minute."
        static let syncStart = "Start sync"
        static let syncSkip = "Skip for now"
        static let syncDone = "All synced!"
        static let notifTitle = "Stay on track"
        static let notifBody = "Get gentle reminders for meals, water, workouts and wind-down — plus your coach's daily brief."
        static let notifAllow = "Enable notifications"
        static let notifSkip = "Maybe later"
        static let finish = "Start using Asclepius"
        static let stepOf = "Step %d of %d"
    }

    enum Today {
        static let goodMorning = "Good morning"
        static let goodAfternoon = "Good afternoon"
        static let goodEvening = "Good evening"
        static let calories = "Calories"
        static let protein = "Protein"
        static let water = "Water"
        static let steps = "Steps"
        static let activeEnergy = "Active energy"
        static let sleep = "Sleep"
        static let streaks = "Streaks"
        static let foodStreak = "food days"
        static let workoutStreak = "workout days"
        static let waterStreak = "water days"
        static let goals = "Goals"
        static let achievements = "Achievements"
        static let weeklyRecap = "Weekly recap"
        static let noGoals = "No active goals — set one in More → Goals."
        static let emptyTitle = "Nothing here yet"
        static let emptyBody = "Log a meal or sync Apple Health to light up your day."
    }

    enum Coach {
        static let title = "Coach"
        static let placeholder = "Ask your coach…"
        static let newChat = "New chat"
        static let newChatConfirm = "Start a new conversation? Your coach still remembers your data and plan."
        static let thinking = "Coach is thinking…"
        static let plan = "Plan"
        static let planTitle = "Your plan"
        static let planEmpty = "No plan yet. Chat with your coach and it will draft one."
        static let planFocus = "Focus areas"
        static let planHistory = "Plan history"
        static let planUpdated = "Updated"
        static let emptyTitle = "Say hello"
        static let emptyBody = "Your coach has read your health data and is ready to help."
        static let needsDataTitle = "Finish setting up"
        static let needsDataBody = "Sync Apple Health or log some data so your coach has something to work with."
        static let briefing = "Morning briefing"
        static let loadOlder = "Load older messages"
        static let suggestionSleep = "How's my sleep?"
        static let suggestionWeek = "Review my week"
        static let suggestionFocus = "What should I focus on?"
    }

    enum Food {
        static let title = "Food"
        static let searchFoods = "Search foods"
        static let searchPrompt = "Search the food database"
        static let favorites = "Favorites"
        static let manualEntry = "Manual entry"
        static let photo = "Analyze a photo"
        static let camera = "Camera"
        static let photoLibrary = "Photo library"
        static let analyzing = "Estimating macros…"
        static let analysisNote = "AI estimate — double-check before saving."
        static let addFood = "Add food"
        static let editEntry = "Review & log"
        static let name = "Name"
        static let meal = "Meal"
        static let quantity = "Quantity"
        static let serving = "Serving"
        static let carbs = "Carbs"
        static let fat = "Fat"
        static let kcal = "Calories (kcal)"
        static let proteinG = "Protein (g)"
        static let carbsG = "Carbs (g)"
        static let fatG = "Fat (g)"
        static let fiberG = "Fiber (g)"
        static let sugarG = "Sugar (g)"
        static let sodiumMg = "Sodium (mg)"
        static let moveTo = "Move to"
        static let logged = "Logged"
        static let emptyMeal = "Nothing logged"
        static let noResults = "No foods matched"
        static let saveAsCustomFood = "Save to my foods"
        static let newFavorite = "New favorite"
        static let editFavorite = "Edit favorite"
        static let favoriteLogged = "Added to your log"
        static let noFavorites = "No favorites yet — save your go-to meals for one-tap logging."
        static let deleteEntry = "Delete entry"
        static let totals = "Totals"
    }

    enum Water {
        static let title = "Water"
        static let add8oz = "+8 oz"
        static let add16oz = "+16 oz"
        static let custom = "Custom"
        static let customTitle = "Add water"
        static let amountMl = "Amount (ml)"
        static let amountOz = "Amount (fl oz)"
        static let history = "Today's entries"
        static let ofGoal = "of goal"
    }

    enum Fitness {
        static let title = "Fitness"
        static let addWorkout = "Log workout"
        static let workoutType = "Type"
        static let activity = "Activity"
        static let duration = "Duration (min)"
        static let distance = "Distance (km)"
        static let energy = "Energy (kcal)"
        static let notes = "Notes"
        static let exercises = "Exercises"
        static let addExercise = "Add exercise"
        static let exerciseName = "Exercise name"
        static let addSet = "Add set"
        static let set = "Set"
        static let reps = "Reps"
        static let weight = "Weight"
        static let prs = "Personal records"
        static let volume = "Training volume"
        static let progression = "Progression"
        static let est1RM = "Est. 1RM"
        static let topSet = "Top set"
        static let sessions = "Sessions"
        static let fromHealthKit = "Apple Health"
        static let emptyTitle = "No workouts yet"
        static let emptyBody = "Log your first session or sync from Apple Health."
        static let thisWeek = "this week"
        static let deleteWorkout = "Delete workout"
        static let noPRs = "Log strength workouts with weights to start setting records."
    }

    enum Sleep {
        static let title = "Sleep"
        static let logSleep = "Log sleep"
        static let asleep = "Asleep (hours)"
        static let inBed = "In bed (hours)"
        static let rem = "REM (hours)"
        static let deep = "Deep (hours)"
        static let avg = "Average"
        static let lastNight = "Last night"
        static let stages = "Stages"
        static let consistency = "Consistency (±h)"
        static let nights = "Nights"
        static let emptyTitle = "No sleep data"
        static let emptyBody = "Sync Apple Health or log a night manually."
        static let stageDeep = "Deep"
        static let stageCore = "Core"
        static let stageREM = "REM"
        static let stageAwake = "Awake"
        static let hoursAsleep = "Hours asleep"
    }

    enum Body {
        static let title = "Body"
        static let logMeasurement = "Log measurement"
        static let metric = "Metric"
        static let value = "Value"
        static let date = "Date"
        static let latest = "Latest"
        static let emptyTitle = "No measurements"
        static let emptyBody = "Log your weight or sync a smart scale to start tracking."
    }

    enum Goals {
        static let title = "Goals"
        static let newGoal = "New goal"
        static let editGoal = "Edit goal"
        static let category = "Category"
        static let label = "Label"
        static let target = "Target"
        static let baseline = "Baseline"
        static let unit = "Unit"
        static let direction = "Direction"
        static let increase = "Increase"
        static let decrease = "Decrease"
        static let maintain = "Maintain"
        static let targetDate = "Target date"
        static let notes = "Notes"
        static let markComplete = "Mark complete"
        static let completed = "Completed"
        static let current = "Current"
        static let emptyTitle = "No goals yet"
        static let emptyBody = "Set a target and your coach will keep you honest."
    }

    enum Achievements {
        static let title = "Achievements"
        static let locked = "Locked"
        static let unlockedOn = "Unlocked"
    }

    enum Weekly {
        static let title = "Weekly report"
        static let vsPrior = "vs prior week"
        static let daysLogged = "Days logged"
        static let avgCalories = "Avg calories"
        static let workouts = "Workouts"
        static let sleepAvg = "Avg sleep"
        static let emptyBody = "Not enough data for a report yet — check back after a few days of tracking."
    }

    enum Settings {
        static let title = "Settings"
        static let account = "Account"
        static let signOut = "Sign out"
        static let signOutConfirm = "Sign out of Asclepius?"
        static let deleteAccount = "Delete account"
        static let deleteConfirmTitle = "Delete your account?"
        static let deleteConfirmBody = "This permanently erases your account and all synced health data on our servers. This cannot be undone."
        static let deleteConfirmAction = "Delete everything"
        static let dailyGoals = "Daily goals"
        static let dailyGoalsFooter = "Targets drive the rings and progress bars across the app."
        static let resetToDefault = "Reset to default"
        static let customized = "Customized"
        static let notifications = "Notifications"
        static let notifMaster = "Reminders"
        static let dnd = "Do not disturb"
        static let dndStart = "From"
        static let dndEnd = "Until"
        static let time = "Time"
        static let healthSync = "Apple Health"
        static let syncNow = "Sync now"
        static let syncing = "Syncing…"
        static let lastSync = "Last sync"
        static let neverSynced = "Never"
        static let units = "Units"
        static let waterInOz = "Show water in fl oz"
        static let about = "About"
        static let privacyPolicy = "Privacy policy"
        static let website = "Website"
        static let version = "Version"
    }

    enum Push {
        static let notificationsDisabled = "Notifications are off for Asclepius. Enable them in Settings."
    }

    enum More {
        static let insights = "Insights"
        static let tracking = "Tracking"
    }
}
