#!/usr/bin/env python3
"""Generate a VAPID keypair for web push and write it into .env.

Web push authenticates the server to the browser's push service with a VAPID
(Voluntary Application Server Identification) ECDSA P-256 keypair:

  * VAPID_PUBLIC_KEY  — the uncompressed public point, base64url-encoded. The
                        frontend passes this to ``pushManager.subscribe`` as the
                        ``applicationServerKey``.
  * VAPID_PRIVATE_KEY — the raw 32-byte private scalar, base64url-encoded. The
                        server signs each push with it (see backend/push.py).
  * VAPID_SUBJECT     — a contact URI (mailto: or https:) required by the spec.

Run once:  ./.venv/bin/python scripts/gen_vapid.py
It is idempotent: if the keys already exist in .env it leaves them alone unless
called with --force (which mints a fresh pair — existing subscriptions, which
are tied to the old public key, would then need to re-subscribe).
"""
from __future__ import annotations

import base64
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec

ENV_PATH = Path(__file__).resolve().parent.parent / ".env"
DEFAULT_SUBJECT = "mailto:asclepius@localhost"


def _b64url(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def generate_keys() -> dict[str, str]:
    """Mint a fresh P-256 keypair, returned as base64url strings."""
    key = ec.generate_private_key(ec.SECP256R1())
    # Raw 32-byte private scalar — what py_vapid.from_raw() expects.
    priv_raw = key.private_numbers().private_value.to_bytes(32, "big")
    # Uncompressed public point (0x04 || X || Y), 65 bytes — the browser's key.
    pub_raw = key.public_key().public_bytes(
        serialization.Encoding.X962,
        serialization.PublicFormat.UncompressedPoint,
    )
    return {
        "VAPID_PUBLIC_KEY": _b64url(pub_raw),
        "VAPID_PRIVATE_KEY": _b64url(priv_raw),
        "VAPID_SUBJECT": DEFAULT_SUBJECT,
    }


def _read_env(path: Path) -> list[str]:
    return path.read_text().splitlines() if path.exists() else []


def _has_key(lines: list[str], key: str) -> bool:
    return any(ln.strip().startswith(f"{key}=") and ln.split("=", 1)[1].strip()
               for ln in lines)


def write_env(values: dict[str, str], force: bool = False) -> bool:
    """Append the VAPID keys to .env. Returns True if anything was written."""
    lines = _read_env(ENV_PATH)
    if not force and all(_has_key(lines, k) for k in values):
        print(".env already has VAPID keys — nothing to do (use --force to replace).")
        return False
    if force:
        # Drop any existing VAPID_* lines so we don't leave a stale pair behind.
        lines = [ln for ln in lines
                 if not ln.strip().startswith(("VAPID_PUBLIC_KEY=",
                                               "VAPID_PRIVATE_KEY=",
                                               "VAPID_SUBJECT="))]
    block = ["", "# Web push (VAPID) keys — generated by scripts/gen_vapid.py."]
    block += [f"{k}={v}" for k, v in values.items()]
    text = "\n".join(lines + block).rstrip("\n") + "\n"
    ENV_PATH.write_text(text)
    return True


def main() -> None:
    force = "--force" in sys.argv[1:]
    keys = generate_keys()
    if write_env(keys, force=force):
        print(f"Wrote VAPID keys to {ENV_PATH}")
        print(f"  Public key (applicationServerKey): {keys['VAPID_PUBLIC_KEY']}")
        print(f"  Subject: {keys['VAPID_SUBJECT']}")


if __name__ == "__main__":
    main()
